apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/{{.ORG}}/{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: nuxeo-sample-final1-web-ui
      context: .
      kaniko:
        dockerfile: Dockerfile
        buildContext:
          localDir: {}
        cache:
          repo: "${DOCKER_REGISTRY}/${ORG}/nuxeo-sample-final1-web-ui/cache"
  cluster:
    namespace: platform
    dockerConfig:
      secretName: jenkins-docker-cfg
